[package]
name = "storb_storage"
description = "Storage interfaces and implementations for Storb"
version.workspace = true
edition.workspace = true

[dependencies]
# Storb
storb_core.workspace = true

thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
blake3.workspace = true
